services:
  ingest-service:
    build:
      context: ../../ingest-service
      dockerfile: Dockerfile
    image: sovra-ingest-service:local
    restart: unless-stopped
    env_file:
      - ../env/.env.docker
    environment:
      OLLAMA_BASE_URL: http://ollama:11434
      EMBEDDING_MODEL: ${EMBEDDING_MODEL:-all-minilm}

      MILVUS_DB_PATH: ${MILVUS_DB_PATH:-/app/milvus/sovra_milvus.db}
      MILVUS_COLLECTION: ${MILVUS_COLLECTION:-sovra_knowledge_base}

      DOCS_PATH: /app/data/docs
      CHUNK_SIZE: ${CHUNK_SIZE:-900}
      CHUNK_OVERLAP: ${CHUNK_OVERLAP:-150}
    volumes:
      - milvus_lite_data:/app/milvus
      - type: bind
        source: ../../data/docs
        target: /app/data/docs
        read_only: true
    ports:
      - "${INGEST_SERVICE_PORT:-8002}:8002"

volumes:
  milvus_lite_data:
    name: sovra_milvus_lite_data

networks:
  default:
    name: sovra-net
    external: true